services:
  signaling-server:
    image: python:3.10-slim
    container_name: signaling-server
    ports:
      - "8071:8071"
    environment:
      - PYTHONUNBUFFERED=1  # Unbuffered stdout/stderr
    volumes:
      - /volume1/docker/signal/app:/app
    working_dir: /app
    command: >
      sh -c "pip install -r requirements.txt &&
             python main_signalingserver.py"